services:
  mozart:
    image: fdekeers/mozart-1.4.0
    container_name: mozart_env
    user: "root" 
    command: tail -f /dev/null
    environment:
      - DISPLAY=${DISPLAY}
      - OZHOME=/usr/mozart
    volumes:
      - ./:/root/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /root/workspace
    network_mode: host
